@baseUrl = http://localhost:8080

### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "pablobreak2017@alu.ufc.br",
  "password": "12345678"
}

> {%
    client.global.set("authToken", "Bearer " + response.body.token);
%}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "User Name",
  "email": "user@example.com",
  "password": "your-password"
}

### Forgot password
POST {{baseUrl}}/users/forgot-password
Content-Type: application/json

{
  "email": "pablobreak2017@alu.ufc.br"
}

### Reset password
PUT {{baseUrl}}/users/reset-password?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCYXJiZVNob3BBUEkiLCJzdWIiOiJwYWJsb2JyZWFrMjAxN0BhbHUudWZjLmJyIiwiaWF0IjoxNzgwNzUxMDcyLCJleHAiOjE3ODA3NTE5NzIsInR5cGUiOiJwYXNzd29yZC1yZXNldCJ9.zVefvtrkqXgBqSOXerS8PG7VCp67mET0zNsxCxJrepCvTPv845FrGc0b8NgRkpToQJceSFeveqJuev-jrawVfg
Content-Type: application/json

{
  "password": "12345678",
  "confirmPassword": "12345678"
}

### Update authenticated user
PUT {{baseUrl}}/users
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Updated Name",
  "email": "updated@example.com",
  "password": "new-password"
}

### Delete authenticated user
DELETE {{baseUrl}}/users
Authorization: {{authToken}}

### Get user by id - ADMIN
GET {{baseUrl}}/users/{{userId}}
Authorization: {{authToken}}

### Get user by email - ADMIN
GET {{baseUrl}}/users/email/{{email}}
Authorization: {{authToken}}

### List users - ADMIN
GET {{baseUrl}}/users?page=0&size=10&sort=name,asc
Authorization: {{authToken}}

### Promote user to admin - ADMIN
PUT {{baseUrl}}/users/{{userId}}/admin
Authorization: {{authToken}}

### Find all tags
GET {{baseUrl}}/tags
Authorization: {{authToken}}

### Find tag by id
GET {{baseUrl}}/tags/98ac13d2-d453-4da6-9d18-c9d54340eaab
Authorization: {{authToken}}

### Create tag
POST {{baseUrl}}/tags
Content-Type: application/json
Authorization: {{authToken}}

{
    "tagName": "Tag Name"
}

### Update tag
PUT {{baseUrl}}/tags/98ac13d2-d453-4da6-9d18-c9d54340eaab
Content-Type: application/json
Authorization: {{authToken}}

{
    "tagName": "Updated Tag Name"
}

### Delete tag
DELETE {{baseUrl}}/tags/98ac13d2-d453-4da6-9d18-c9d54340eaab
Authorization: {{authToken}}

### Associate tag with user
POST {{baseUrl}}/users/me/tags
Content-Type: application/json
Authorization: {{authToken}}

{
    "tagIds": [
      "71f68257-a625-42c6-ac12-9cb6d2efd831"
    ]
}

### Disassociate tag from user
DELETE {{baseUrl}}/users/me/tags/71f68257-a625-42c6-ac12-9cb6d2efd831
Authorization: {{authToken}}

### Create venue - ADMIN
POST {{baseUrl}}/venues
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Theatro São João",
  "number": "123",
  "city": "Sobral",
  "street": "Praça São João",
  "neighborhood": "Centro",
  "landmark": "Em frente à praça principal",
  "hasParkingLot": false,
  "hasAccessibility": true,
  "hasBathroom": true,
  "hasFoodsAndDrinks": false
}

### List venues (Pagination) - USER/ADMIN
GET {{baseUrl}}/venues?page=0&size=10
Authorization: {{authToken}}

### Search venues with filters - USER/ADMIN
GET {{baseUrl}}/venues/search?city=Sobral&neighborhood=Centro&name=Theatro
Authorization: {{authToken}}

### Get venue by id - USER/ADMIN
GET {{baseUrl}}/venues/8f74bf2f-a78d-4ead-8f8e-1a5a597484a2
Authorization: {{authToken}}

### Update venue - ADMIN
PUT {{baseUrl}}/venues/8f74bf2f-a78d-4ead-8f8e-1a5a597484a2
Content-Type: application/json
Authorization: {{authToken}}

{
  "hasParkingLot": true,
  "hasFoodsAndDrinks": true,
  "landmark": "Ao lado da nova cafeteria"
}

### Delete venue - ADMIN
DELETE {{baseUrl}}/venues/8f74bf2f-a78d-4ead-8f8e-1a5a597484a2
Authorization: {{authToken}}