spring:
  application:
    name: mova

  datasource:
    url: ${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5434/postgres}

    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    open-in-view: false

    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}

    show-sql: ${SHOW_SQL:true}

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
  servlet:
    context-path: /mova

app:
  jwtSecret: ${JWT_SECRET:MySecretKeyDefaultToDevelopment}
  jwtExpirationInMs: ${JWT_EXPIRATION:86400000}